SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `PHIBASEDB` ;
CREATE SCHEMA IF NOT EXISTS `PHIBASEDB` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `PHIBASEDB` ;

-- -----------------------------------------------------
-- Table `PHIBASEDB`.`CSPPERFU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PHIBASEDB`.`CSPPERFU` ;

CREATE  TABLE IF NOT EXISTS `PHIBASEDB`.`CSPPERFU` (
  `PFUCPFUAK` VARCHAR(2) NOT NULL ,
  `PFUDPFUAF` VARCHAR(45) NOT NULL ,
  `PFUIACTSF` VARCHAR(1) NOT NULL ,
  PRIMARY KEY (`PFUCPFUAK`) )
ENGINE = InnoDB
COMMENT = 'Perfil de Usuario';


-- -----------------------------------------------------
-- Table `PHIBASEDB`.`CSPSERSI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PHIBASEDB`.`CSPSERSI` ;

CREATE  TABLE IF NOT EXISTS `PHIBASEDB`.`CSPSERSI` (
  `SSICSSIAK` VARCHAR(5) NOT NULL ,
  `SSINSSIAF` VARCHAR(45) NOT NULL ,
  `SSIDSSIAF` VARCHAR(80) NOT NULL ,
  `SSIDURLAF` VARCHAR(256) NOT NULL ,
  `SSIICONAF` VARCHAR(256) NOT NULL ,
  `SSIIPROSF` VARCHAR(1) NOT NULL ,
  `SSIIDESSF` VARCHAR(1) NOT NULL ,
  `SSIIACTSF` VARCHAR(1) NOT NULL ,
  PRIMARY KEY (`SSICSSIAK`) )
ENGINE = InnoDB
COMMENT = 'SERVICIO DEL SISTEMA';


-- -----------------------------------------------------
-- Table `PHIBASEDB`.`CSPSERPF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PHIBASEDB`.`CSPSERPF` ;

CREATE  TABLE IF NOT EXISTS `PHIBASEDB`.`CSPSERPF` (
  `PFUCPFUAK` VARCHAR(2) NOT NULL ,
  `SSICSSIAK` VARCHAR(5) NOT NULL ,
  `SVPIACTSF` VARCHAR(1) NOT NULL ,
  PRIMARY KEY (`PFUCPFUAK`, `SSICSSIAK`) )
ENGINE = InnoDB
COMMENT = 'SERVICIOS DE PERFIL DE USUARIO';


-- -----------------------------------------------------
-- Table `PHIBASEDB`.`CSPPARSI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PHIBASEDB`.`CSPPARSI` ;

CREATE  TABLE IF NOT EXISTS `PHIBASEDB`.`CSPPARSI` (
  `PSICPARAK` VARCHAR(4) NOT NULL ,
  `PSIDPARAF` VARCHAR(80) NOT NULL ,
  `PSITPARVF` VARCHAR(1) NOT NULL ,
  `PSIVALPAF` VARCHAR(256) NOT NULL ,
  PRIMARY KEY (`PSICPARAK`) )
ENGINE = InnoDB
COMMENT = 'PARAMETRO SISTEMA';


-- -----------------------------------------------------
-- Table `PHIBASEDB`.`USMUSUAR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PHIBASEDB`.`USMUSUAR` ;

CREATE  TABLE IF NOT EXISTS `PHIBASEDB`.`USMUSUAR` (
  `USUEMAIAK` VARCHAR(60) NOT NULL ,
  `USUNUSUAF` VARCHAR(60) NOT NULL ,
  `USUPASSAF` VARCHAR(64) NOT NULL ,
  `PFUCPFUAK` VARCHAR(2) NOT NULL ,
  `USUESTAVF` VARCHAR(1) NOT NULL ,
  `USUILOGNF` INT NOT NULL ,
  `USUTBLONF` DECIMAL(13,0) NOT NULL ,
  `USUPASCSF` VARCHAR(1) NOT NULL ,
  `USUFULCFF` DATE NOT NULL ,
  PRIMARY KEY (`USUEMAIAK`) )
ENGINE = InnoDB
COMMENT = 'USUARIO SISTEMA';


-- -----------------------------------------------------
-- Table `PHIBASEDB`.`USDBLOQU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PHIBASEDB`.`USDBLOQU` ;

CREATE  TABLE IF NOT EXISTS `PHIBASEDB`.`USDBLOQU` (
  `USUEMAIAK` VARCHAR(60) NOT NULL ,
  `USUTBLONF` DECIMAL(13,0) NOT NULL ,
  `BLUILOGNF` INT NOT NULL ,
  `BLUTDESNF` DECIMAL(13,0) NOT NULL ,
  `USUEMADAF` VARCHAR(60) NOT NULL ,
  `BLUDAUTSF` VARCHAR(1) NOT NULL ,
  PRIMARY KEY (`USUEMAIAK`, `USUTBLONF`) )
ENGINE = InnoDB
COMMENT = 'HISTORICO BLOQUEOS USUARIO';


-- -----------------------------------------------------
-- Table `PHIBASEDB`.`USDLOGIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PHIBASEDB`.`USDLOGIN` ;

CREATE  TABLE IF NOT EXISTS `PHIBASEDB`.`USDLOGIN` (
  `USUEMAIAK` VARCHAR(60) NOT NULL ,
  `LIUFECHFK` DATE NOT NULL ,
  `LIUNSECNK` INT NOT NULL ,
  `LIUHORATF` TIME NOT NULL ,
  `LIUDIRIAF` VARCHAR(30) NOT NULL ,
  `LIUIEXISF` VARCHAR(1) NOT NULL ,
  PRIMARY KEY (`USUEMAIAK`, `LIUFECHFK`, `LIUNSECNK`) )
ENGINE = InnoDB
COMMENT = 'LOG INGRESO USUARIO';


-- -----------------------------------------------------
-- Table `PHIBASEDB`.`USDLOGQU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PHIBASEDB`.`USDLOGQU` ;

CREATE  TABLE IF NOT EXISTS `PHIBASEDB`.`USDLOGQU` (
  `USUEMAIAK` VARCHAR(60) NOT NULL ,
  `LQUFECHFK` DATE NOT NULL ,
  `LQUNSECNK` INT NOT NULL ,
  `LQUHORATF` TIME NOT NULL ,
  `LQUTEXTAF` VARCHAR(8192) NOT NULL ,
  `LQURESPAF` VARCHAR(8192) NOT NULL ,
  `LQUPARQAF` VARCHAR(8192) NOT NULL ,
  `LQUDESCAF` VARCHAR(256) NOT NULL ,
  PRIMARY KEY (`USUEMAIAK`, `LQUFECHFK`, `LQUNSECNK`) )
ENGINE = InnoDB
COMMENT = 'LOG QUERY USUARIO';


-- -----------------------------------------------------
-- Table `PHIBASEDB`.`SEPCONCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PHIBASEDB`.`SEPCONCE` ;

CREATE  TABLE IF NOT EXISTS `PHIBASEDB`.`SEPCONCE` (
  `COSCCOSAK` VARCHAR(2) NOT NULL ,
  `COSDCOSAF` VARCHAR(60) NOT NULL ,
  `COSRDFTAF` VARCHAR(120) NOT NULL ,
  `COSNRELNF` INT NOT NULL ,
  `COSCCOPAK` VARCHAR(2) NOT NULL ,
  `COSDOCUAF` VARCHAR(120) NOT NULL ,
  PRIMARY KEY (`COSCCOSAK`) )
ENGINE = InnoDB
COMMENT = 'CONCEPTO SEMANTICO';


-- -----------------------------------------------------
-- Table `PHIBASEDB`.`SEPRELCO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PHIBASEDB`.`SEPRELCO` ;

CREATE  TABLE IF NOT EXISTS `PHIBASEDB`.`SEPRELCO` (
  `COSCCOSAK` VARCHAR(2) NOT NULL ,
  `RCOCRCOAK` VARCHAR(2) NOT NULL ,
  `RCODRCOAF` VARCHAR(60) NOT NULL ,
  `RCORDFRAF` VARCHAR(120) NOT NULL ,
  `RCORANGAF` VARCHAR(120) NOT NULL ,
  `RCODOCUAF` VARCHAR(120) NOT NULL ,
  PRIMARY KEY (`COSCCOSAK`, `RCOCRCOAK`) )
ENGINE = InnoDB
COMMENT = 'RELACIÓN CONCEPTO SEMÁNTICO';


-- -----------------------------------------------------
-- Table `PHIBASEDB`.`SEDCONCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PHIBASEDB`.`SEDCONCE` ;

CREATE  TABLE IF NOT EXISTS `PHIBASEDB`.`SEDCONCE` (
  `DCONSECNK` INT NOT NULL AUTO_INCREMENT ,
  `DCOIRICAF` VARCHAR(256) NOT NULL ,
  `COSCCOSAK` VARCHAR(2) NOT NULL ,
  PRIMARY KEY (`DCONSECNK`) )
ENGINE = InnoDB
COMMENT = 'DETALLE CONCEPTO SEMÁNTICO';


-- -----------------------------------------------------
-- Table `PHIBASEDB`.`SEDRELCO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PHIBASEDB`.`SEDRELCO` ;

CREATE  TABLE IF NOT EXISTS `PHIBASEDB`.`SEDRELCO` (
  `DCONSECNK` INT NOT NULL ,
  `DRCNSECNK` INT NOT NULL ,
  `DRCVALRAF` VARCHAR(256) NOT NULL ,
  `COSCCOSAK` VARCHAR(2) NOT NULL ,
  `RCOCRCOAK` VARCHAR(2) NOT NULL ,
  PRIMARY KEY (`DCONSECNK`, `DRCNSECNK`) )
ENGINE = InnoDB
COMMENT = 'DETALLE RELACIÓN CONCEPTO SEMÁNTICO';



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
